on: [push]

jobs:
  validate_openapi:
    runs-on: ubuntu-latest
    name: Validate OpenAPI definitions
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenAPI validator
        run: npm install -g @redocly/cli
      - name: Validate definitions
        run: redocly lint Swagger/*.yaml
        env:
          NODE_NO_WARNINGS: 1
